version: '3.8'

services:
  sandbox:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
      - 5173:5173
    environment:
      - HOST=0.0.0.0
      - VITE_HOST=0.0.0.0
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    tty: true